# Generated by Django 5.2.8 on 2025-12-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Varlık Adı')),
                ('sembol', models.CharField(max_length=20, unique=True, verbose_name='Yahoo Kodu')),
                ('kategori', models.CharField(choices=[('EMTIA', 'Emtia (Altın, Petrol)'), ('FOREX', 'Forex (Döviz)'), ('KRIPTO', 'Kripto Para'), ('BORSA_TR', 'BIST 100 Hisseleri'), ('BORSA_US', 'ABD Borsası')], default='FOREX', max_length=20)),
                ('aktif', models.BooleanField(default=True, verbose_name='Listede Göster')),
            ],
            options={
                'verbose_name': 'Finansal Varlık',
                'verbose_name_plural': 'Finansal Varlıklar',
            },
        ),
    ]
