# Generated by Django 6.0 on 2025-12-31 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varlik',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Portfoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Eldeki Miktar (Adet/Lot)')),
                ('maliyet', models.FloatField(verbose_name='Ortalama Maliyet ($/TL)')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('varlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analiz.varlik', verbose_name='Varlık')),
            ],
            options={
                'verbose_name': 'Portföy Kaydı',
                'verbose_name_plural': 'Portföyüm',
            },
        ),
    ]
